# Generated by Django 4.2.4 on 2023-11-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_product_alter_book_options_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountProduct',
        ),
        migrations.CreateModel(
            name='DiscountedProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.product',),
        ),
    ]
