# Generated by Django 4.2.4 on 2023-10-23 18:11

from django.db import migrations


def set_age_group(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')
    persons = person_model.objects.all()

    for person_record in persons:
        if person_model.age <= 12:
            person_record.age_group = 'Child'
        elif person_model.age <= 17:
            person_record.age_group = 'Teen'
        else:
            person_record.age_group = 'Adult'
    person_model.objects.bulk_update(persons, ['age_group'])


def set_age_group_default(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')
    age_group_default = person_model._meta.get_field("age_group").default

    for person in person_model.objects.all():
        person.age_group = age_group_default
        person.safe()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_person'),
    ]

    operations = [
        migrations.RunPython(set_age_group, reverse_code=set_age_group_default)
    ]
