# Generated by Django 4.2.4 on 2023-10-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_migration_delivery_warranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('release_year', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='statues',
            field=models.CharField(choices=[('P', 'Pending'), ('Cpd', 'Completed'), ('Cnd', 'Canceled')], max_length=30),
        ),
    ]
