# Generated by Django 4.2.4 on 2023-10-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='is_magical',
            field=models.BooleanField(default=False),
        ),
    ]
